services:
  sendgrid-bedrock: 
    build: .
    image: sendgrid-bedrock-local
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - INFERENCE_PROFILE_ARN=us.anthropic.claude-3-5-sonnet-20240620-v1:0 # This can an ARN or a cross-region profie
      - TABLE_NAME=CR-local-ConversationRelayAppDatabase
      - AWS_REGION=us-east-1
      - STACK_USE_CASE=restaurantOrderingUseCase
      # THERE MUST BE A SLASH AT THE END OF THE URL - TWILIO DOES NOT LIKE IT WITHOUT IT
      - WS_URL=wss://dfe9-75-85-156-88.ngrok-free.app/
    secrets:
      - source: aws
        target: /home/node/.aws
        uid: "1000"
        gid: "1000"
        mode: 0700
    ports:
      - "3000:3000"

secrets:
  aws:
    file: "~/.aws"